package com.ashchuk.popularmoviesone.data.pojo;

/**
 * Created by Artyom Koshko (@ashchuk) on 11.03.2018.
 * Generated by http://www.jsonschema2pojo.org/
 */


import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Genre {

    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("name")
    @Expose
    private String name;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}